### ISSUE TITLE
Provide symlinks "<configDir>/run/<package>" -> "<configDir>/temp/<temp-package-dir>"

### ISSUE THREAD

**Issue by chreekat** [snoyberg/keter#101]
Motivation for this is that we have certain executables that are run by cron that I would like to include in the package. In order for cron to find the executable, it needs to be discoverable or located at a fixed location. Creating a symlink that stays synced with the currently-running version of a package seems the most straightforward way of achieving this.

I'm looking into implementing this myself, but any pointers (or other suggestions) are welcome.

**Comment by creichert** [comment]
As a quick workaround, you could also look into using a Keter background
job to create or refresh a symlink to the bundled app.

https://github.com/snoyberg/keter/blob/master/incoming/foo1_0/config/keter.yaml#L17

The only caveat would be to ensure the app has successfully launched. I
believe the webapp will be fully activated when the background job is
started.

Just a quick thought!

**Comment by chreekat** [comment]
I like it! Simple and flexible. I'm going to make sure it works for me, and then I'll close this as unnecessary.

**Comment by chreekat** [comment]
Sad news. While the worker won't start until the app has launched, it has no way of knowing if ensureAlive will be successful. I'll think about this more tomorrow.

**Comment by chreekat** [comment]
Ok, here's what I think. In the short term, I'm going to cowboy a solution, with a worker like

    mkSymlink
    while sleep 65
    do
        symlinkHealthy || mkSymlink
    done

In the long run, I think what I *really* want is a different feature altogether: #102
