### ISSUE TITLE
post-shutdown actions?

### ISSUE THREAD

**Issue by mwotton** [snoyberg/keter#114]
couldn't find any relevant info in the sample configs - is there a hook for executing code on shutdown? In particular, I'd like to copy .prof and .hp files out and put them in a dated artifacts folder so I can analyse performance later.

**Comment by creichert** [comment]
Do you mean you want an app to be able to execute code right before it's
being shutdown? Are the .prof and .hp properly terminated?

There was a similar request recently for adding more signal handling
capabilities to keter: https://github.com/snoyberg/keter/issues/102

Keter does deliver a SIGTERM to kill the app somewhat gracefully so you
could try catching the SIGTERM and executing you're code from within the
app or with a small wrapper script which executes the app and uses
`trap` to catch the signal.

A quick workaround hack, which i'm hesitant to suggest and not even sure
will work properly, could be to:

```
stanza:
  - type: webapp
    exec: ../path/to/app && cp *.prof *.hp /folder
```

Be careful with that one as I didn't test it. I would try catching the
signal first. Let me know if either of these works out.

**Comment by mwotton** [comment]
I'm not exactly sure, but i think the profile file only gets created on exit - if i catch SIGTERM, then it won't be there until it's too late, if you see what i mean. it's more something that should be executed after shutdown. I guess I could write a shell wrapper that caught sigterm, delivered it and moved the file... I'll try that.

**Comment by creichert** [comment]
I briefly looked if there was a way to set the paths explicitly in the
RTS opts with no luck.

Using the wrapper script might be a decent workaround but I think some
kind of hook might be useful, in general.

**Comment by mwotton** [comment]
well, obviously i agree :) i'll do the workaround for now.

**Comment by mwotton** [comment]
in case anyone else wants the magic/horror:

```
#!/bin/bash
./web +RTS -N12 -p -hc &
webPID=$!
trap "export dir=/var/profiles/`date '+%F-%T'`; echo \$dir; mkdir \$dir;  mv *.prof *.hp \$dir; kill $webPID" SIGTERM SIGINT
wait $webPID
```

**Comment by creichert** [comment]
@mwotton I'm assuming this is working sufficiently for you're current use case. I've added a section to the Feature Wishlist in the wiki for now.

**Comment by mwotton** [comment]
fair enough.

**Comment by jappeace** [comment]
can we in general just first send a sigint, wait a while ask for the process status, and then send sigterm if it didn't die?
it's implmeneted here: https://github.com/snoyberg/keter/blob/master/src/Keter/App.hs#L354
monitored process is also in the keter tree: https://github.com/snoyberg/keter/blob/master/src/Keter/Conduit/Process/Unix.hs#L348

I'll merge fixes that'd make your life easier and don't interupt existing functionality.
Feel free to make a suggestion PR.
