### ISSUE TITLE
can't recognized hostname base on keter.yaml

### ISSUE THREAD

**Issue by MonrealRyan** [snoyberg/keter#134]
Keter always tells me that 
```The hostname you have provided, 192.*.*.*, is not recognized.```

since I access it in my browser using its IP.
here is my keter.yaml file.
```
exec: ../dist/bin/AppName
args:
    - production
hosts: 
    - 192.*.*.*
    - app.com
```

also on Keter log Output the last to line says:
```
2016-01-28 17:55:44.97: Reserving hosts for app AppName: 
2016-01-28 17:55:44.97: Activating app AppName with hosts: 
```

**Comment by tolysz** [comment]
Maybe `"192.*.*.*"` but I am not sure if stars can go that way. It is not a regex it is like tree of domains.

This is quite uncommon to want to have "192.0.0.0/8" as the host would need to have those IP there.
I would try "*" as well, this one will catch everything and maybe move "app.com" as the first.

**Comment by MonrealRyan** [comment]
Thanks for the guide, it is working now. 
never mind the asterisk. :+1:
