### ISSUE TITLE
`env` doesn’t work without `stanzas`

### ISSUE THREAD

**Issue by gasi** [snoyberg/keter#135]
I had to switch to `stanzas` based configuration to get `env` variables to work, see: https://github.com/gasi/zoomhub/commit/270a062390e21e8813c621c7d79033b74779ce1b

Note: In the commit above, `env` use `-` (dash) listed enviromnent variables, but I also tried without the dashes before.

Now that I switched to `stanzas`, everything works great and I ❤️ this project!

**Comment by creichert** [comment]
Cool project! The v0.4 config doesn't have support for `env`. I think adding support for `env` in 0.4 would not be difficult, but it might be better to encourage users to simply use the `stanzas` based config.

**Comment by gasi** [comment]
Ah, my bad then! You’re right, I inadvertently combined the config from the README.md

```
exec: ../path/to/executable
host: mydomainname.example.com
```

…with the following `stanzas` based one… https://github.com/snoyberg/keter/blob/304cf84bd9ced7176d56341d64d86c39c3c1b542/incoming/foo1_0/config/keter.yaml#L7-L8

I think you’re right, it might be good to update the `README.md` docs to start with the `stanzas` based config right away. How about the following?

```
stanzas:
  - type: webapp
    exec: ../path/to/executable
    host: mydomainname.example.com
```

I’ll close the ticket then.

_P.S. Glad you like our project, @creichert_ :smile:
