### ISSUE TITLE
Should setup-keter.sh still be using Platform?

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/keter#136]
```
sudo apt-get install postgresql haskell-platform -y
```

From: https://raw.githubusercontent.com/snoyberg/keter/master/setup-keter.sh

**Comment by snoyberg** [comment]
I agree with this, it should use Stack instead. @creichert any objection?

**Comment by creichert** [comment]
No objections, I'm looking at this now (hopefully the changes are small).

**Comment by creichert** [comment]
@bitemyapp Fixed in #138, let me know if you see any problems. I'll merge it soon, thanks!
