### ISSUE TITLE
need app-specific dynamic configuration via environment variables 

### ISSUE THREAD

**Issue by mwotton** [snoyberg/keter#139]
in general, if you have secrets you need to use in an app, the 12-factor approach is to set them in persistent environment variables, as in https://devcenter.heroku.com/articles/config-vars

This is useful because

1. it's easy to set different variables for staging, QA and production deploys, without hard-coding them in the repo.
2. you can give access to the source code repository to people without exposing all your credentials.

the global keter config.yml is there, but doesn't provide a way of scoping environment variables to a particular app.

Is there a suggested way of managing this?

**Comment by creichert** [comment]
Currently, there isn't a direct way to manage this with keter.

One thing I've done recently is to generate the keter.yaml as part of the build process when deploying an app. This lets me generate and embed the secrets in the `env` before deployment which works especially well from CI where I can store production keys safely.

I've also worked with solutions more like `dotenv` for ruby by managing the env files as part of the build or deploy process. e.g. using `.env.development` file for development and getting the variables from the env when deploying from CI.

Hope that helps, I'd be happy to give more detail if you want.

**Comment by mwotton** [comment]
That still requires a redeploy unfortunately. We have since dropped keter
and are managing our own process runners as a result of this, which is a
pity, but I guess it means this is closeable
