### ISSUE TITLE
How do we use Keter with Cloudflare's free SSL certs?

### ISSUE THREAD

**Issue by jezen** [snoyberg/keter#156]
Normally when I publish a static site, I stick it behind a Cloudflare _Always Use HTTPS_ page rule. I don't need to manually fiddle with certificates; it Just Works™.

How does this work with Keter? It looks as though Keter doesn't allow HTTPS unless I physically put an SSL certificate on my server.

**Comment by tolysz** [comment]
Do you use free or paid cets from CF?
If the free ones CF will contact keter via HTTP, and the real IP is hidden to the world, but the world will see  HTTPS.
I usually use both infinite caching for the static site via separate full cloaked website and for the application bit I use letsencrypt ( https://github.com/kappataumu/letsencrypt-cloudflare-hook )

**Comment by jezen** [comment]
I use their free certificates.

With the _letsencrypt-cloudflare-hook_, I'll need to manually put the certificate on my server, right?

I'm guessing there's no way to make HTTPS work on Keter without putting a certificate on the server. Am I right?

**Comment by tolysz** [comment]
This ( https://video-cdn.kio.sx/ )  is SSL proxied via  CF
You simply WORLD <-> CF:443 -> YOU(PRIVATE):80
Yes, with a hook you could use per bundle certificates

**Comment by jezen** [comment]
Some rough notes on getting _Keter_, _Let's Encrypt_, and _CloudFlare_ all working together:

1. Sign into CloudFlare
2. Set up DNS
3. Disable CloudFlare (clouds should not be orange)
4. Run this stuff on your server:
    ```
    apt-get update
    apt-get -y install letsencrypt
    letsencrypt certonly --standalone -d <yourdomainhere.com>
    ```

5. Enable CloudFlare for both A records (clouds should become orange again)
6. Set 'always use HTTPS' page rule
7. Set SSL to 'Full' under Crypto

After these steps, _Let's Encrypt_ should automatically renew certificates. Everything should just work and you can forget about it.
