### ISSUE TITLE
How to configure keter/nginx for Real-IP ?

### ISSUE THREAD

**Issue by alebon** [snoyberg/keter#157]
I have two apps running on keter (port 8111) behind nginx (port 80). How can I configure keter to pick up the X-Real-IP header ? (Or is this configured in Yesod?) 
I have already tried to set "ip-from-header: _env:IP_FROM_HEADER:true"

**Comment by tolysz** [comment]
Is the main config: `# ip-from-header: true`
https://github.com/snoyberg/keter/blob/master/etc/keter-config.yaml
not working?

**Comment by alebon** [comment]
No :(

I have in nginx: 
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Real-IP $remote_addr;

Keter config:
ip-from-header: true

Yesod application settings:
ip-from-header: "_env:IP_FROM_HEADER:true"


Am I missing something? :/

**Comment by alebon** [comment]
Whoops, sorry, I just missconfigured things :/
