### ISSUE TITLE
[question] Is The Postgres Plugin Actually Useful?

### ISSUE THREAD

**Issue by jezen** [snoyberg/keter#177]
Forgive my ignorance; I don't know what I don't know.

If I understand correctly, the Postgres plugin is designed to generate a random postgres user name, password, and database name.

Is it desirable to have random values here? Does that not make it more cumbersome to move an application from one server to another? For example if you make regular database backups, then migrate to a new server and want to import the latest backup, do you not then have to update all those values in the backup?

**Comment by creichert** [comment]
Sounds like you're right. I supply my credentials in the environment, in general, but I think this feature could be useful in some testing scenarios. 

Are you still using it?
