### ISSUE TITLE
Hostname not recognized (ensureAlive failed)

### ISSUE THREAD

**Issue by davewripley** [snoyberg/keter#236]
I'm trying to deploy a yesod app using keter. The app seems to work ok using `yesod devel`, but not via keter yet. Trying to load the page in a browser, I get "Welcome to Keter The hostname you have provided, FOO, is not recognized." Looking at the keter log, I see Sanity checks passed, then Reserving hosts, then Process created --- then exactly 90 seconds later Forgetting host reservations, then `Error occurred when launching bundle APP: ensureAlive failed`. I assume this is user error, but I'm a bit stymied as to how to proceed! What should I be checking?

**Comment by jappeace** [comment]
your app log, it failed to bind to a port,
in that keter working directory (`root`) there is a folder called logs, 
one is for keter itself, the other one is for your app.

**Comment by jappeace** [comment]
I made that error a bit more verbose, thanks!
the other possibility is that your firewall blocks port detection, 
but a firewall setup like that seems unlikely because it'd have to block connections from and to localhost.

**Comment by jeongoon** [comment]
I had the same problem. are you using Scaffolding?
because keter is trying to put environ variable into your app  via `PORT` to open new arbitrary(random?) port
but Scaffolding `settings.yaml` says "I will use `YESOD_PORT`

```
port:           "_env:YESOD_PORT:3000" # NB: The port `yesod devel` uses is distinct from this value.
```

so, that should be changed to

```
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value.
```

I guess it would be great if `yesod keter` command should change automatically on behalf of user.

**Comment by jeongoon** [comment]
or how about keter also inform user something like  "may be check your app is using environment variable "PORT"? because this is yesod problem, but give user more hints.

**Comment by jappeace** [comment]
Good idea, I added that as well.

**Comment by davewripley** [comment]
The change from YESOD_PORT to PORT completely sorted it out! Thanks so much for this!
