### ISSUE TITLE
Better error message for missing sudo

### ISSUE THREAD

**Issue by joyfulmantis** [snoyberg/keter#238]
Currently, when keter is running in an environment without sudo, and requires it (global setuid config, or postgres plugin) it fails with the extremely cryptic error message: "Invalid argument (bad file descriptor)". It would be much better if in these scenarios it simply says something like "Unable to find sudo, are you sure it is installed on your computer?"

This should be a relatively easy fix, and if the maintainers agree with the necessity of this change and the direction of this solution, I am happy to try to get a pull request fixing it in the next couple of days.

**Comment by jappeace** [comment]
yes, sure, make a PR
