### ISSUE TITLE
SQLite db in temp?

### ISSUE THREAD

**Issue by davewripley** [snoyberg/keter#239]
I've got a yesod app built on the yesod/sqlite template. It works as expected with `yesod devel`, with the `.sqlite3` db in the repo's root directory. Deploying with keter, it kind of works, except that the `.sqlite3` file is created in `/opt/keter/temp/APP-0/`, and so does not survive things like a restart. Is there a quick way to have keter handle a SQLite db in a more persistent location?

**Comment by jappeace** [comment]
I'd set a sqlite path in your settings.yaml,
and then tell persistent to use that path in the connection string:

+ https://hackage.haskell.org/package/persistent-sqlite-2.13.1.0/docs/Database-Persist-Sqlite.html#v:mkSqliteConnectionInfo
+ https://www.connectionstrings.com/sqlite/

You probably want to set that path to something else for development. But the production should always point to the same, eg `/var/lib/db/prod.db`

**Comment by davewripley** [comment]
Okay; thanks much! This is a yesod question, then, not a keter thing. Much appreciated!
