### ISSUE TITLE
Use fastlogger instead of homegrown logging system

### ISSUE THREAD

**Issue by jappeace** [snoyberg/keter#257]
Currently, keter has a homegrown logging system.
It does a couple of things:
1. logs keter issues to a file
2. logs the apps keter runs to seprate files per app.

We need to retain that behavior!

But, I think it's best if we move away from the homegrown logging and use
the fast-logger library instead: https://hackage.haskell.org/package/fast-logger-3.1.1/docs/System-Log-FastLogger.html

So we likely need multiple of those, one per app.
For keter itself we then can get rid of that log message type and use monadlogger instead.

**Comment by RiugaBachi** [comment]
TODO:
- Migrate Conduit.LogFile -> `fast-logger`
- Get rid of `log` from `AppManager` + log type ADT -> migrate `snoyberg/monadlogger`
- Update config to add `rotateLogs` (default False)
- Implement behavior for logging to stderr by default if not rotating logs

Will try to get a draft PR up sometime tonight.

**Comment by RiugaBachi** [comment]
Regarding implementation of log file rotation using `fast-logger`:

- If we use baked-in `LogFile` (which rotates) -> there is no callback to specify file naming in a backwards compatible way. It is hardcoded to rotate in the style of `<file>` `<file>.1` `<file>.2`, etc.
  * We can go ahead with this, bump the major version, and eat the backwards compatibility loss. 
  * Benefit is that we can get rid of any in-house rotation logic, which is the most significant part of the module we're trying to simplify with this rewrite.
- If we handroll the rotation logic,
  * Will still need in-house rotation logic; so perhaps benefits won't be as large as anticipated.
  * Upside is backwards compatibility is preserved.
- If we use `LogFileTimedRotate` -> it is not the intended purpose of this logger type (logging rotation based on time intervals), but we get a callback to do whatever we want in IO, ex. check file size, rotate if necessary.
  * Honestly it's significantly less obscure and hacky to just handroll the rotation logic even if it's _marginally_ longer. I don't advocate for this, just documenting why it's a  terrible idea.

**Comment by jappeace** [comment]
As we discussed, we'll break naming convention.

The primary reason being that if people are using automated scripts to pipe logs into some other system, they're likely quite interested into the new stderr option as well. Which is more robust.

**Comment by RiugaBachi** [comment]
Leaving this for future reference later: "%Y%m%d_%H%M%S.log" <- old log rotation naming format'

**Comment by RiugaBachi** [comment]
Draft PR up on #273 , continuing discussion there.
