### ISSUE TITLE
keter uses up memory - space leak?

### ISSUE THREAD

**Issue by schoettl** [snoyberg/keter#280]
I run keter 2.1.0 on NixOS 23.05. I run two similar Yesod apps with it. One works fine but as soon as I copy the second keter bundle in the incoming directory, keters memory usage climbs from 2% to 80% making the old server (4GB RAM + 2GB swap) unusable.

My current workaround is to start the second Yesod app manually and reconfigure the nginx reverse proxy.

Any ideas why keter needs so much memory? I would be less surprised if the Yesod app would take that memory.

I just wanted to leave this as a notice. Maybe I can do more testing after my holidays.

**Comment by jappeace** [comment]
I don't know, we'd need to investigate/profile it.

**Comment by schoettl** [comment]
I close this until I have time to investigate it. I currently live with the work-around for this one app.
