### ISSUE TITLE
Support tar-0.6

### ISSUE THREAD

**Issue by Bodigrim** [snoyberg/keter#286]
`keter` demands `tar < 0.6`, prohibiting a recently released https://hackage.haskell.org/package/tar-0.6.0.0. 
Cf. https://github.com/commercialhaskell/stackage/issues/7202

```
$ cabal build -c 'tar>0.6' --allow-newer='keter:tar'
[ 5 of 21] Compiling Keter.TempTarball

src/Keter/TempTarball.hs:78:12: error: [GHC-83865]
    • Couldn't match type ‘[Char]’ with ‘Tar.TarPath’
      Expected: Tar.Entries Tar.FormatError
                -> Tar.GenEntries
                     Tar.TarPath
                     FilePath
                     (Either
                        (Either Tar.FormatError Tar.DecodeLongNamesError)
                        Tar.FileNameError)
        Actual: Tar.Entries Tar.FormatError
                -> Tar.GenEntries
                     FilePath
                     FilePath
                     (Either
                        (Either Tar.FormatError Tar.DecodeLongNamesError)
                        Tar.FileNameError)
```

https://github.com/snoyberg/keter/blob/16bd88c1e1e572ffa0bc90afa8b9843269e85045/src/Keter/TempTarball.hs#L73-L78

This could be potentially fixed, but the real question is why `keter` re-implements [`Codec.Archive.Tar.unpack`](https://hackage.haskell.org/package/tar-0.6.0.0/docs/Codec-Archive-Tar.html#v:unpack)?

**Comment by Bodigrim** [comment]
Git history points to https://github.com/snoyberg/keter/commit/e0fa8d7baca298097cde92e200db5d1993c5212b, but I cannot find any context.

**Comment by jappeace** [comment]
I don't know, I guess I'd have to compare implementations side by side?

**Comment by Bodigrim** [comment]
The latest `tar` release at the moment of e0fa8d7baca298097cde92e200db5d1993c5212b was https://hackage.haskell.org/package/tar-0.4.0.1. `Codec.Archive.Tar.unpack` is here: https://hackage.haskell.org/package/tar-0.4.0.1/docs/src/Codec-Archive-Tar-Unpack.html#unpack

`keter` implementation of `Codec.Archive.Tar.unpack`:
* ignores symlinks completely (does it matter for `keter`?).
* makes an effort to write files manually, not relying on `Data.ByteString.Lazy.writeFile`. This might be needed to combat lazy I/O opening too many file descriptors at once, dunno. @snoyberg any recollection on this?

**Comment by snoyberg** [comment]
No recollection

**Comment by jappeace** [comment]
guess we'll replace it with the lib and pray?

**Comment by jappeace** [comment]
PR: https://github.com/snoyberg/keter/pull/287
