### ISSUE TITLE
Error occured when launching bundle "xxx": FileNotExecutable

### ISSUE THREAD

**Issue by schoettl** [snoyberg/keter#291]
I found a regression in keter. When I copy a keter bundle to `incoming`, keter comes up with this error:

```
Keter.AppManager:283|Error> Error occured when launching bundle "xxxx": FileNotExecutable "etc/../temp/xxxx-5/config/../dist/bin/xxxx"
```

-> keter version: 2.1.2 -> works

-> keter version: 2.1.5 -> does not work

I suspect version 2.1.4 (bump package versions, tls, warp and zlib).
The extracted file dist/bin/xxxx is in fact not executable but when I manually extract it with `tar -vxf bundle.keter`, it is.

**Comment by jappeace** [comment]
please use cabal bounds as a workaround,
you can also use bounds to validate it's 2.1.4 causing this.

**Comment by jappeace** [comment]
I suspect this is caused by tar tough since that deals with permissions :thinking:

**Comment by jappeace** [comment]
I'll make a minor release for tar >= 0.6.x

**Comment by jappeace** [comment]
I released

**Comment by Bodigrim** [comment]
For the reference, this was fixed in https://github.com/haskell/tar/pull/26.
