### ISSUE TITLE
Provide full stanza based config file example.

### ISSUE THREAD

**Issue by angerman** [snoyberg/keter#57]
Figuring out the options for the stanza based configuration files is very unclear :-(
Additional documentation with respect to the stanza based configuration files would be much appreciated.

I'd be glad to help out, but haven't found where I'd extract all the options from in the source.  Any pointers where to start?

**Comment by creichert** [comment]
@angerman I'm going to close this issue but if you need more documentation in certain areas feel free to reopen.

As a side not, I would like to make some of the example apps more useful out of the box. For example, I want to try out a bundle which sets up an `apt-cacher-ng` proxy. I've detailed some of this in the wiki so feel free to update it.
