### ISSUE TITLE
"premature end of compressed stream" Error When Pushing New Bundle

### ISSUE THREAD

**Issue by creichert** [snoyberg/keter#66]
When launching a completely new site, I often get this message printed in the keter current.log file.

```
Error occured when launching bundle testsite: Codec.Compression.Zlib: premature end of compressed stream
```

This does not break anything and only happens when pushing new bundles.

I will make an attempt to look at this soon, if noone does in the meantime.

**Comment by tolysz** [comment]
Can this one be related to just closed one?
Because if pushing was killing some LabalMap allocations it would stop reading.

**Comment by MonrealRyan** [comment]
@creichert - i have the same error when putting another bundle in my ``/opt/keter/incoming`` what did you do to prevent it? thank you in advance.

**Comment by CarstenKoenig** [comment]
I just had this too but it seems that `yesod keter` will produces *damaged* files (trying to unpack them will yield this error)

If I bundle up manually `tar ...` it works

**Comment by creichert** [comment]
@tolysz I think you may be right. Either way, this is not an issue for me anymore.
