### ISSUE TITLE
Getting "keter: no keys found" message, even though key is present

### ISSUE THREAD

**Issue by hansler** [snoyberg/keter#69]
I just finished configuring keter (latest version), and everything works with the exception of https. Keter starts fine, but when I visit the https version of my site, it doesn't load, and keter gives me the message "keter: no keys found".

Here is my keter-config.yaml file:

    root: ..
    
    listeners:
        # HTTP
        - host: "*4" # Listen on all IPv4 hosts
          port: 80 # Could be used to modify port
        # HTTPS
        - host: "*4"
          port: 443
          key: key.pem
          certificate: certificate.pem

The files "key.pem" and "certificate.pem" are located in the same directory as the config file. I've tried multiple keys/certs and I still get the same issue. My key.pem looks like this:

    -----BEGIN PRIVATE KEY-----
    <snipped>
    -----END PRIVATE KEY-----

I receive the same error message if I replace the contents of "key.pem" with any random gibberish, which leads be to believe that the key file isn't getting parsed correctly. Not sure if it's a bug in keter or if I'm doing something wrong. Thanks!

**Comment by snoyberg** [comment]
That error message most likely comes from:

https://github.com/vincenthz/hs-tls/blob/f4749ba2bef244afbf88678b65b9c2aa2d181e9d/core/Network/TLS/Credentials.hs#L38

It probably implies that your key.pem file is not compatible with the tls package. Can you try loading it with `credentialLoadX509` and see what happens?

**Comment by hansler** [comment]
You're right; credentialLoadX509 uses the readKeyFile function, and this happens:

    Prelude Data.X509.File> readKeyFile "key.pem"
    []

Per RapidSSL's instructions, I generated the key file using
    openssl req -new -newkey rsa:2048 -nodes -keyout key.pem -out key.csr

Do you know how I'd go about generating a key.pem file that is compatible?

**Comment by snoyberg** [comment]
These instructions have worked for me:

https://github.com/yesodweb/wai/tree/master/warp-tls#warp-tls

**Comment by hansler** [comment]
Thanks, that did the trick. I wonder what the difference is - they should both be 2048 bit RSA keys...

**Comment by snoyberg** [comment]
It may be worth opening an issue with the hs-tls repo about this.

**Comment by hansler** [comment]
I opened the issue with vincenthz/hs-certificate (same maintainer), as I believe the issue is there. Thanks for the quick help!
