### ISSUE TITLE
How to access deployed project

### ISSUE THREAD

**Issue by MonrealRyan** [snoyberg/keter#78]
Hi sorry about this issue, i'm run out of ideas of how to access my deployed project on our main domain server.

I installed properly the keter, put the ```.keter``  file in the ```/opt/keter/incoming``` path but once i access it on the browser it always see the nginx page.

Also I use fpcomplete IDE for my project and I just download the file executable file there.

Thank in advance

**Comment by creichert** [comment]
@MonrealRyan Are you running nginx as well?

I would go into `/opt/keter` and run:

```
$ ./bin/keter etc/keter-config.yml
```

What is the output?

**Comment by MonrealRyan** [comment]
@creichert  - Yes sir.

here the ouput of the command.

keter: etc/../log/keter/current.log: rename: permission denied (Permission denied)

**Comment by creichert** [comment]
@MonrealRyan  Can  you run it with root permissions (sudo)?

**Comment by MonrealRyan** [comment]
@creichert - This is the result sir.

```
keter: etc/certificate.pem: openBinaryFile: does not exist (No such file or directory)
```

**Comment by creichert** [comment]
Modify your keter-config.yaml and remove the references to ssl certs.

I would comment this out:
https://github.com/snoyberg/keter/blob/master/etc/keter-config.yaml#L14-L17

**Comment by MonrealRyan** [comment]
Hi it runs....

i try the code you gave to me... thank you... :)

On Sat, Mar 7, 2015 at 3:17 AM, Christopher Reichert <
notifications@github.com> wrote:

> @MonrealRyan <https://github.com/MonrealRyan> Can you run it with root
> permissions (sudo)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snoyberg/keter/issues/78#issuecomment-77618208>.
>



-- 
Ryan N. Monreal
*Web Developer*

*onlineJobs.ph <http://www.onlinejobs.ph/jobseekers/info/169394>*

**Comment by creichert** [comment]
Great, is everything working well for you? Feel free to open another issue if you have more questions.

**Comment by MonrealRyan** [comment]
Thank you

**Comment by MonrealRyan** [comment]
@creichert  - follow question about this link;
https://github.com/snoyberg/keter/blob/master/etc/keter-config

how do i get that ssl? or the file my keter-config.yaml accessing?

**Comment by creichert** [comment]
@MonrealRyan I'm sorry, I don't understand the question. Are you trying to get ssl working?

You can create self-signed certificates locally for testing.  The process for keter is essentially the same as nginx:
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04


Does that help?

**Comment by MonrealRyan** [comment]
@creichert  - my site always produce ``` Something went wrong ```

what does it mean?

**Comment by MonrealRyan** [comment]
@creichert  - u stop my nginx then reload again..

now the produces this message on my site.

```
Welcome to Keter

The hostname you have provided, www.mysite.com, is not recognized.

```

please help me.
