### ISSUE TITLE
Why does keter depend on network-conduit-tls?

### ISSUE THREAD

**Issue by ygale** [snoyberg/keter#83]
The cabal file for keter specifies a dependency on network-conduit-tls, but a quick grep through the source code didn't turn up any import of `Data.Conduit.Network.TLS`. Is that dependency really needed?

The reason I am asking is that I just added chain certificate support to keter via #82, using chain certificate support I previously added to tls and warp-tls. However, network-conduit-tls does not yet support chain certificates in its credentials. My tests indicate that keter does seem to support chain certificates now without any change to network-conduit-tls. And anyway, it's always a good idea to get rid of unneeded dependencies.

**Comment by snoyberg** [comment]
It could be there for historical purposes. If you can compile it without dependency, please feel free to send a PR.

**Comment by creichert** [comment]
Fixed now. Thanks again!

**Comment by ygale** [comment]
I actually went ahead and added chain certificate support to network-conduit-tls, for completeness, while it's still fresh in my mind, via snoyberg/conduit#203. But if the dependency isn't needed here, better to get rid of it.
