### ISSUE TITLE
Incorrect header check

### ISSUE THREAD

**Issue by MonrealRyan** [snoyberg/keter#85]
Hi,
I was on updating our server file on ``/opt/keter/incoming``. 
but once i put my update ``*.keter`` bundle file on the ``/opt/keter/incoming`` it gives mes this error log:

`` Error occured when launching bundle Main: Codec.Compression.Zlib: incorrect header check ``

hope you help me. thank you

**Comment by MonrealRyan** [comment]
i want to add a another question - is this error is a keter problem? or Error On how my project has been setup?

**Comment by MonrealRyan** [comment]
Hi everyone,

i already solve it. It's just that you need to compress properly the ``*.keter`` file.

i use this code tar ``tar -zcvpf *.keter``

**Comment by MaxGabriel** [comment]
@MonrealRyan You can also use `yesod keter` to make a keter file.

**Comment by MonrealRyan** [comment]
@MaxGabriel - i'm using FP Complete IDE the don't produce a keter file. so i do it manually. but thank you :)
