### ISSUE TITLE
Uploaded files - deleted once it update *.Keter bundle

### ISSUE THREAD

**Issue by MonrealRyan** [snoyberg/keter#90]
Hi,
I have some uploaded files that i want to be remain when i update my ``*keter`` bundle in the ``/opt/keter/incoming``.

how do i do that? 

thank you.

**Comment by snoyberg** [comment]
Store it in a different directory than the explicit named "temp" directory that your current directory is set to by default.

**Comment by MonrealRyan** [comment]
@snoyberg - where should i do that? ``/opt/keter/etc/keter-config.yaml``

**Comment by snoyberg** [comment]
You need to modify your application.

**Comment by MonrealRyan** [comment]
do you have some instruction for this? can you provide me the url? 

thank you.

**Comment by BlakeRain** [comment]
What I believe Michael means is that you will probably want to store your uploaded files in a directory which does not get destroyed by keter when a new bundle is uploaded, something like `/var/lib/<app>/uploads`.

Of course, one might prefer to use something like S3, and store the bucket identifier in the database.

**Comment by MonrealRyan** [comment]
@BlakeRain - thank you for more clear explanation. :+1: 
@snoyberg  - thank you :)
