### ISSUE TITLE
Web socket connection dies in exact 5 minutes when app server by keter

### ISSUE THREAD

**Issue by geraldus** [snoyberg/keter#91]
Hi Michael!

I'm using **keter** on my VPS, and I really like it! Current version running is `1.3.5`. Server has Debian Wheezy installed. There is no other web servers running, I use `keter` alone. I'm facing odd issue: web socket connection always dies after 5 minutes.

As a minimal test case I've used web socket example grabbed here: https://github.com/jaspervdj/websockets/blob/master/example/server.lhs. The only changes I've done to original code are:

+ changed server address to `127.0.0.1`
+ added required PORT variable check

I've used simples keter config to this application:

    exec: ../websockets
    host: 185.53.168.20

and then bundled and deployed this stuff to my VPS.

I can't see anything helpful in keter logs, expect standard `websockets`' error message "websockets: ConnectionClosed". This is not occurs locally. As you can see in source code there is `forkPingThread` used, but connection dies even if it was in active use all the time. Example code uses `websockets` library only, no `WAI` or `WARP`.

What could be possible reason of this behaviour? I asked VPS support about possible connection time limits, but they answered me, that there is no limitations, and all VPS are just standard Xen based servers. Could it be something specific to Debian itself or is there some other linux settings (sorry I'm not a specialist at this things)?

**Comment by snoyberg** [comment]
This is actually caused by keter, see: https://github.com/snoyberg/keter/commit/65c313590895da29922e1865d57bfe971f36bf25. I think the right solution here may be to make the 5 minute time bound optional via a setting in the main keter config file, what do you think?

**Comment by geraldus** [comment]
Oh, you made my day! Having time bound configurable sounds good to me. Would be very glad to provide PR for this.

**Comment by snoyberg** [comment]
Awesome, thank you. Let me know if you have any questions.

**Comment by geraldus** [comment]
@snoyberg, but what about #29 ? Is it resolved by mentioned commit or there was permanent solution for `warp` itself already?

**Comment by snoyberg** [comment]
IIRC, I was never able to reliably reproduce #29, so I'm not certain. That's why I want to make this optional.

**Comment by geraldus** [comment]
@snoyberg sorry for delay (having big troubles with internet access at office). Do I understood correctly, that I need to extend `KeterConfig` from `V10` module and do not touch `AppConfig` from `V04`?

**Comment by snoyberg** [comment]
Yes that sounds right.

**Comment by geraldus** [comment]
@snoyberg should I extend both V04 and V10 `KeterConfig`s?

**Comment by geraldus** [comment]
Since almost all stuff is new for me I need some guidance. Is it acceptable to open work in progress PR and push stuff step by step squashing everything into single commit in the final? Hope this is not overkill.

**Comment by tolysz** [comment]
@geraldus  You can always work on your own fork, then squash it and do PR :)

**Comment by geraldus** [comment]
@tolysz oh, of course.
@snoyberg  one thing that could be very annoying is that I use `stylish-haskell` on save, and all imports are reordered and aligned, should I disable it to preserve original import order?

**Comment by tolysz** [comment]
@geraldus :) I simply did not see any new branch in your repo. I would disable s-h. And maybe propose next PR to make code beautiful.

**Comment by snoyberg** [comment]
>  should I extend both V04 and V10

I would only do V10 personally. But if you're still using the old style config files (without stanzas), then you'd need to extend V04 as well.

**Comment by geraldus** [comment]
For now I've done simplest part: extended both config data types (https://github.com/geraldus/keter/commit/5f6eeff0c520ce02550422f756b8cd1556708f35). Now I need to figure out all places where config is used and see what updates should be done. Didn't figured out what is the best way to extract current settings inside `withClient` function yet.

**Comment by geraldus** [comment]
@snoyberg , ok, finally I've got some time to continue work on this. So, `Proxy.withClient` is only used by `Proxy.reverseProxy`; the latter is only used in `Main` module by `startListening` function. Neither `withClient` nor `reverseProxy` know nothing about app configuration, but `startListening` does. So I have two options: pass config (or just time bound) to `reverseProxy` and `withClient` adding extra parameter to these functions functions; or to apply `timeout` function to whole `runAndBlock` call. But last option seems to me wrong. What can you say?

**Comment by snoyberg** [comment]
I agree, passing in the argument is the right approach here.

**Comment by geraldus** [comment]
Closing this because of  https://github.com/snoyberg/keter/pull/92
