### ISSUE TITLE
[Question] Postgres plugin

### ISSUE THREAD

**Issue by geraldus** [snoyberg/keter#95]
Sorry for noise, I just switched to the latest Yesod's scaffold and to PostgreSQL from MySQL, I know **keter** provides some Postgres support out-of-box. As I can see, the web application should accept database connection settings through environment variables, so does it means that database is being recreated each time new version of app bundle is uploaded (in other words the question is data preserved when bundle updated)?

**Comment by tolysz** [comment]
Database is created once, then connection setting as saved inside `keter` config folder on the server as `postgres.yaml`.
Next time you upload bundle with the same _name_ it reuses that settings.

**Comment by geraldus** [comment]
@tolysz cool, thank you!
