### ISSUE TITLE
/opt/keter/temp/reloaded-6/dist/build/reloaded/reloaded: 6: /opt/keter/temp/reloaded-6/dist/build/reloaded/reloaded: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by patrickcorrigan** [snoyberg/keter#98]
I get this error when trying to deploy the yesod sacffolding site. My keter version is 1.4.0.1. Any ideas? Thank you so much.

**Comment by tolysz** [comment]
Does your `keter.yml` have any `)`?

**Comment by patrickcorrigan** [comment]
Wow thank you for the quick response. No there are no `)`.

**Comment by patrickcorrigan** [comment]
```

# A Keter app is composed of 1 or more stanzas. The main stanza will define our
# web application. See the Keter documentation for more information on
# available stanzas.
stanzas:

  # Your Yesod application.
  - type: webapp

    # Name of your executable. You are unlikely to need to change this.
    # Note that all file paths are relative to the keter.yml file.
    exec: ../dist/build/reloaded/reloaded

    # Command line options passed to your application.
    args: []

    hosts:
      # You can specify one or more hostnames for your application to respond
      # to. The primary hostname will be used for generating your application
      # root.
      - http://52.25.131.199/

    # Enable to force Keter to redirect to https
    # Can be added to any stanza
    requires-secure: false

  # Static files.
  - type: static-files
    hosts:
      - static.reloaded.com
    root: ../static

    # Uncomment to turn on directory listings.
    # directory-listing: true

  # Redirect plain domain name to www.
  - type: redirect

    hosts:
      - http://52.25.131.199/
    actions:
      - host: http://52.25.131.199/
        # secure: false
        port: 80

    # Uncomment to switch to a non-permanent redirect.
    # status: 303

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming

# If you would like to have Keter automatically create a PostgreSQL database
# and set appropriate environment variables for it to be discovered, uncomment
# the following line.
# plugins:
#   postgres: true
```

**Comment by patrickcorrigan** [comment]
The binary can run on my local machine.

**Comment by patrickcorrigan** [comment]
When trying to run the binary on the amazon server I get the same error as when keter tries to run it.

**Comment by patrickcorrigan** [comment]
Oh dear. The ghc version that is running on the server is 7.6. Updating now.

**Comment by tolysz** [comment]
So, it might not be `keter` :)

but try removing: ~~http://~~ 52.25.131.199 ~~/~~
and comment `redirect` block

**Comment by patrickcorrigan** [comment]
No you are right. It's not keter. Any idea how to fix it? Is it the dynamic linking of libraries for my binary? I have installed the same version of ghc on the server now using this ppa https://launchpad.net/~hvr/+archive/ubuntu/ghc/+index?batch=75&direction=backwards&memo=75

**Comment by creichert** [comment]
@patrick How are you compiling your binary? Why do you need GHC on the server?

Are you running linux locally? If so, you need to compile the binary on your machine and copy that to the server.

If you can, show us the sequence of commands you are using.

**Comment by patrickcorrigan** [comment]
No I'm running OS X locally. To create my binary I run `yesod keter` in the root of my project. I then use `scp` to upload it to the server. I can run the binary that is built by `yesod keter` locally but when I untar the dot keter file on the server and try to run the binary I get a Syntax error: ")" unexpected

**Comment by MaxGabriel** [comment]
Binaries built by GHC on OS X won't run on Linux (I'm not sure if this should be an absolute statement, or if with some effort you could get cross compilation working). Try running `yesod keter` from a Linux VM running the same operating system as your server and scping that to your server. 

I know it's not recommended for production sites because compiling on GHC is resource intensive and competes running your web app, but if this is a small project you could probably get away with compiling the project on the same server that you're running the executable on.

**Comment by patrickcorrigan** [comment]
Thanks Max :) Out of curiosity why is that? I'll do that thank you very much :+1:

**Comment by geraldus** [comment]
@patrickcorrigan have a look at **Docker**<sup>[1]</sup>. My host OS is `OS X` and I'm using `docker` to build binaries for my VPS. BTW, any progress on this? Is it still relevant?
[1]:https://www.docker.com
